name: QA Env Run app only test cases alc_4348 alc_4349 alc_4956

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: 'x64'
          cache: 'maven'

      - name: Install npm version 9.4.2
        run: npm install -g npm@9.4.2

      - name: Install Maven dependencies
        run: mvn -f pom-mobile.xml install

      - name: Get Latest Build Number
        id: get_build_number
        shell: pwsh
        run: |
          $response = Invoke-RestMethod -Uri "https://mobile-api.lambdatest.com/mobile-automation/api/v1/builds?limit=1" -Method Get -Headers @{
            Authorization = "Basic $([Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('ashish.rawatfleekitsolutions:MWAa6go8FynMFZt5GYZyeKtSycfc6I2YKQhFn1PH2h1Tw6Syo2')))"
          }
          $build_id = $response.data[0].build_id
          Write-Host "Build ID: $build_id"
          echo "BUILD_ID=$build_id" >> $env:GITHUB_ENV

      - name: Generate Shareable Link
        id: generate_shareable_link
        shell: pwsh
        run: |
          $build_id = $env:BUILD_ID
          $requestBody = @{
            entityIds = @($build_id)
            entityType = "App Automation Build"
            expiresAt = 7
          } | ConvertTo-Json -Compress
          $response = Invoke-RestMethod -Uri "https://api.lambdatest.com/lshs/api/v1.0/share-item/generate-sharable-link" -Method Post -Headers @{
            Authorization = "Basic $([Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes('ashish.rawatfleekitsolutions:MWAa6go8FynMFZt5GYZyeKtSycfc6I2YKQhFn1PH2h1Tw6Syo2')))"
            'Content-Type' = 'application/json'
          } -Body $requestBody
          $shareUrl = $response.shareIdUrl
          Write-Host "Shareable Report URL: $shareUrl"
          echo "SHAREABLE_URL=$shareUrl" >> $env:GITHUB_ENV

      - name: Send Notification to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SHAREABLE_URL: ${{ env.SHAREABLE_URL }}
        run: |
          $headers = @{
            'Content-Type' = 'application/json'
          }
          $body = @{
            text = "QA Env Mobile App (PB_QA_20082024(R05)) only Test Cases Automated Execution Completed. Open this link to check the report: $env:SHAREABLE_URL"
          } | ConvertTo-Json
          Invoke-RestMethod -Uri $env:SLACK_WEBHOOK -Method Post -Headers $headers -Body $body
